### ISSUE TITLE
Web support (currently flutter beta branch)

### ISSUE THREAD

**Issue by PaznerA** [atlanhq/darwin-camera#15]
Is possible to get a pemissions to access webcam via browser for better cross platform compatibility?
I'm new in Flutter & Dart so, I can't make it right now :worried:

**Comment by askprateek** [comment]
Hi @PaznerA, You might be able to get permission to access the webcam. But This plugin won't be able to help to capture or record using a webcam. 

This plugin doesn't support capturing images/videos from the desktop/laptop webcam. It's made for Android and iOS at the moment.

**Comment by askprateek** [comment]
Adding more context around this issue.
We are using a Flutter camera to power our package, which doesn't support the web at the moment. This package is made by the official flutter development team.

Adding a link to the package for reference
https://pub.dev/packages/camera

cc @PaznerA
